### ISSUE TITLE
Handle AZ

### ISSUE THREAD

**Issue by smaftoul** [squarescale/sqssh#3]
We currently already support AZ in configuration like this:

```
  - name: whatever
    filters:
      - Name: availability-zone
        Values: eu-west-1a
```

Though, with the current setup, we would , for example, for our case, need to define worker-1 -> AZ-a , worker2 -> AZ-b ... , which will be lot more verbose.

We need to find a solution , either in the config file, or on command line flags, or env vars, or by using a special format for the user@hosts (and / or a combination of those) to be able de easily choose a host on an AZ.
